[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.7.21" }
com-github-johnrengelman-shadow = { id = "com.github.johnrengelman.shadow", version = "7.1.2" }
com-google-protobuf = { id = "com.google.protobuf", version = "0.9.4" }
org-jlleitschuh-gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.0" }

[libraries]
vertx-stack-depchain = { group = "io.vertx", name = "vertx-stack-depchain", version = "4.5.3" }
protobuf-kotlin = { group = "com.google.protobuf", name = "protobuf-kotlin", version = "3.25.3" }
protoc = { group = "com.google.protobuf", name = "protoc", version = "3.25.3" }
protoc-gen-grpc-java = { group = "io.grpc", name = "protoc-gen-grpc-java", version = "1.61.1" }
protoc-gen-grpc-kotlin = { group = "io.grpc", name = "protoc-gen-grpc-kotlin", version = "1.4.1" }
grpc-kotlin-stub = { group = "io.grpc", name = "grpc-kotlin-stub", version = "1.4.1" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "5.9.1" }
